import type { Pasillo, Receta, Tiempo } from './types'

/**
 * El recetario que viene con la app. No se sube a la nube: es igual en todos
 * los teléfonos y se va llenando conforme publique versiones nuevas. Lo que
 * ustedes escriban vive aparte, en el estado, y eso sí viaja.
 *
 * Los pasos están escritos para alguien que no cocina seguido: sin "sofreír
 * hasta acitronar" ni medidas de chef. La idea es que cualquiera pueda pararse
 * en la cocina y sacarlo.
 */

const v = (que: string, cuanto?: string) => ({ que, cuanto, pasillo: 'verdura' as Pasillo })
const c = (que: string, cuanto?: string) => ({ que, cuanto, pasillo: 'carne' as Pasillo })
const l = (que: string, cuanto?: string) => ({ que, cuanto, pasillo: 'lacteos' as Pasillo })
const a = (que: string, cuanto?: string) => ({ que, cuanto, pasillo: 'abarrotes' as Pasillo })

export const RECETARIO: Receta[] = [
  // ------------------------------------------------------------- almuerzo
  {
    id: 'r-huevos-mexicana',
    titulo: 'Huevos a la mexicana',
    tiempos: ['almuerzo'],
    minutos: 15,
    porciones: 4,
    ingredientes: [
      a('Huevo', '8'),
      v('Jitomate', '2'),
      v('Cebolla', '1/2'),
      v('Chile serrano', '1'),
      a('Aceite', '1 cucharada'),
      a('Sal', 'al gusto'),
      a('Tortillas', '1 paquete'),
      a('Frijoles de la olla', '1 taza'),
    ],
    pasos: [
      'Pica chiquito el jitomate, la cebolla y el chile. Si no quieres que pique, quítale las semillas al chile.',
      'Pon el aceite en el sartén a fuego medio y echa la cebolla. Muévela un minuto, hasta que se vea transparente.',
      'Agrega el jitomate y el chile. Déjalo 3 minutos moviendo de vez en cuando.',
      'Rompe los huevos en un plato hondo, bátelos con un tenedor y échalos al sartén.',
      'Mueve despacio hasta que cuajen, unos 3 minutos. Sal al final.',
      'Calienta tortillas y sirve con frijoles.',
    ],
    nota: 'Si sobra, al día siguiente sale un burrito con tortilla de harina.',
  },
  {
    id: 'r-chilaquiles-verdes',
    titulo: 'Chilaquiles verdes',
    tiempos: ['almuerzo'],
    minutos: 25,
    porciones: 4,
    ingredientes: [
      a('Totopos', '1 bolsa grande'),
      v('Tomate verde', '10'),
      v('Chile serrano', '2'),
      v('Cebolla', '1/2'),
      v('Ajo', '2 dientes'),
      v('Cilantro', 'un manojito'),
      l('Crema', '1 bote chico'),
      l('Queso fresco', '200 g'),
      a('Huevo', '4'),
      a('Caldo de pollo en polvo', '1 cucharadita'),
    ],
    pasos: [
      'Pon a hervir los tomates verdes con los chiles, media cebolla y el ajo, cubiertos de agua. 10 minutos, hasta que el tomate cambie de color.',
      'Pásalos a la licuadora con un poco de esa agua, el cilantro y el caldo en polvo. Licua.',
      'Vacía la salsa en una olla ancha y déjala hervir 5 minutos a fuego bajo.',
      'Apaga, echa los totopos y revuelve rápido para que se bañen todos. No los dejes mucho o se aguadan.',
      'Sirve y encima: crema, queso desmoronado y cebolla en rueditas.',
      'Aparte, fríe los huevos estrellados y ponlos arriba.',
    ],
  },
  {
    id: 'r-molletes',
    titulo: 'Molletes',
    tiempos: ['almuerzo', 'cena'],
    minutos: 15,
    porciones: 4,
    ingredientes: [
      a('Bolillos', '4'),
      a('Frijoles refritos', '1 lata o 2 tazas'),
      l('Queso manchego rallado', '250 g'),
      v('Jitomate', '2'),
      v('Cebolla', '1/4'),
      v('Cilantro', 'un poco'),
      v('Limón', '1'),
    ],
    pasos: [
      'Parte los bolillos a la mitad y sácales un poco del migajón con los dedos.',
      'Úntales frijoles y encima el queso.',
      'Mételos al horno o al tostador hasta que el queso se derrita, unos 8 minutos.',
      'Mientras: pica jitomate, cebolla y cilantro, ponles limón y sal. Esa es la salsa de encima.',
    ],
    nota: 'Lo más rápido que hay cuando ya es tarde y nadie quiere cocinar.',
  },
  {
    id: 'r-quesadillas',
    titulo: 'Quesadillas de queso con champiñones',
    tiempos: ['almuerzo', 'cena'],
    minutos: 20,
    porciones: 4,
    ingredientes: [
      a('Tortillas de maíz', '12'),
      l('Queso oaxaca', '400 g'),
      v('Champiñones', '250 g'),
      v('Cebolla', '1/2'),
      v('Epazote', 'unas hojas'),
      a('Aceite', '1 cucharada'),
    ],
    pasos: [
      'Rebana los champiñones y pica la cebolla.',
      'En un sartén con aceite, echa la cebolla, luego los champiñones y el epazote. Sal. Cocínalos 8 minutos, hasta que suelten el agua y se seque.',
      'Deshebra el queso.',
      'Calienta las tortillas, ponles queso y champiñones, dóblalas y déjalas en el comal hasta que el queso se derrita.',
    ],
  },
  {
    id: 'r-hot-cakes',
    titulo: 'Hot cakes',
    tiempos: ['almuerzo'],
    minutos: 20,
    porciones: 4,
    ingredientes: [
      a('Harina para hot cakes', '2 tazas'),
      l('Leche', '1 1/2 tazas'),
      a('Huevo', '2'),
      l('Mantequilla', 'un trozo'),
      a('Miel de maple', 'al gusto'),
      v('Plátano', '2'),
    ],
    pasos: [
      'Bate la harina con la leche y los huevos hasta que no queden grumos. Déjala reposar 5 minutos.',
      'Calienta el sartén a fuego medio-bajo y úntalo con poquita mantequilla.',
      'Vacía un cucharón de mezcla. Cuando le salgan burbujas arriba, voltéalo. Un minuto más y listo.',
      'Sirve con plátano en rodajas y miel.',
    ],
    nota: 'A las niñas les gusta hacerlos: que ellas volteen.',
  },
  {
    id: 'r-avena',
    titulo: 'Avena con plátano y canela',
    tiempos: ['almuerzo'],
    minutos: 10,
    porciones: 4,
    ingredientes: [
      a('Avena', '1 1/2 tazas'),
      l('Leche', '4 tazas'),
      v('Plátano', '2'),
      a('Canela', '1 raja'),
      a('Azúcar', 'al gusto'),
    ],
    pasos: [
      'Pon la leche con la raja de canela a fuego medio hasta que empiece a soltar el hervor.',
      'Echa la avena y mueve. Baja el fuego y déjala 5 minutos moviendo de vez en cuando.',
      'Endulza al gusto y sirve con plátano en rodajas.',
    ],
  },
  {
    id: 'r-sincronizadas',
    titulo: 'Sincronizadas de jamón',
    tiempos: ['almuerzo', 'cena'],
    minutos: 15,
    porciones: 4,
    ingredientes: [
      a('Tortillas de harina', '8'),
      c('Jamón', '250 g'),
      l('Queso manchego', '300 g'),
      v('Aguacate', '1'),
    ],
    pasos: [
      'Pon una tortilla en el comal, encima queso, jamón y otra vez queso.',
      'Tápala con otra tortilla y aplástala tantito.',
      'Voltéala cuando la de abajo esté dorada. Espera a que el queso se derrita.',
      'Pártela en cuatro y sirve con aguacate.',
    ],
  },

  // --------------------------------------------------------------- comida
  {
    id: 'r-tinga',
    titulo: 'Tinga de pollo',
    tiempos: ['comida', 'cena'],
    minutos: 40,
    porciones: 4,
    ingredientes: [
      c('Pechuga de pollo', '700 g'),
      v('Jitomate', '5'),
      v('Cebolla', '1'),
      v('Ajo', '2 dientes'),
      a('Chipotles en adobo', '1 lata chica'),
      a('Caldo de pollo en polvo', '1 cucharadita'),
      a('Aceite', '2 cucharadas'),
      a('Tostadas', '1 paquete'),
      l('Crema', '1 bote chico'),
      l('Queso fresco', '200 g'),
      v('Lechuga', '1/2'),
    ],
    pasos: [
      'Pon la pechuga a hervir en agua con un pedazo de cebolla, un ajo y sal. 25 minutos. Guarda un poco del caldo.',
      'Sácala, déjala enfriar tantito y deshébrala con las manos o con dos tenedores.',
      'Licua los jitomates con el otro ajo, un pedazo de cebolla, 2 chipotles y un poco del caldo.',
      'Rebana el resto de la cebolla en tiras y fríela en el aceite 3 minutos.',
      'Echa la salsa licuada, deja que hierva 5 minutos y prueba de sal y de picor: si quieres más, agrega otro chipotle.',
      'Agrega el pollo deshebrado y déjalo 10 minutos a fuego bajo para que agarre sabor.',
      'Sirve sobre tostadas con lechuga, crema y queso.',
    ],
    nota: 'Rinde mucho. Lo que sobre sirve para tacos o tortas al día siguiente.',
  },
  {
    id: 'r-pollo-salsa-verde',
    titulo: 'Pollo en salsa verde con arroz',
    tiempos: ['comida'],
    minutos: 45,
    porciones: 4,
    ingredientes: [
      c('Piezas de pollo', '4'),
      v('Tomate verde', '12'),
      v('Chile serrano', '2'),
      v('Cebolla', '1'),
      v('Ajo', '2 dientes'),
      v('Cilantro', 'un manojo'),
      a('Arroz', '1 1/2 tazas'),
      a('Aceite', '3 cucharadas'),
      a('Caldo de pollo en polvo', '1 cucharada'),
    ],
    pasos: [
      'Hierve los tomates verdes con los chiles y un pedazo de cebolla, 10 minutos.',
      'Licúalos con el ajo, el cilantro y un poco del agua donde hirvieron.',
      'En una olla, dora las piezas de pollo con un poco de aceite y sal, 5 minutos por lado.',
      'Échales la salsa encima, tapa y déjalo a fuego bajo 25 minutos.',
      'Para el arroz: fríelo en 2 cucharadas de aceite hasta que se vea blanco, échale 3 tazas de agua caliente con el caldo en polvo, tapa y no lo destapes en 18 minutos.',
    ],
  },
  {
    id: 'r-milanesas',
    titulo: 'Milanesas empanizadas con puré',
    tiempos: ['comida'],
    minutos: 40,
    porciones: 4,
    ingredientes: [
      c('Milanesas de res', '4'),
      a('Pan molido', '2 tazas'),
      a('Huevo', '3'),
      v('Papa', '6'),
      l('Leche', '1/2 taza'),
      l('Mantequilla', 'un trozo'),
      a('Aceite', 'para freír'),
      v('Limón', '2'),
    ],
    pasos: [
      'Pon las papas a hervir en agua con sal, peladas y partidas, 20 minutos, hasta que se deshagan al picarlas.',
      'Bate los huevos en un plato hondo. En otro, pon el pan molido con sal y pimienta.',
      'Pasa cada milanesa por huevo y luego por pan molido, apretándola bien para que se pegue.',
      'Fríelas en aceite caliente, 3 minutos por lado, hasta que estén doradas. Sácalas sobre servilleta.',
      'Escurre las papas y machácalas con la mantequilla y la leche caliente. Sal al gusto.',
      'Sirve con limón.',
    ],
  },
  {
    id: 'r-albondigas',
    titulo: 'Albóndigas en caldillo',
    tiempos: ['comida'],
    minutos: 50,
    porciones: 4,
    ingredientes: [
      c('Carne molida de res', '700 g'),
      a('Arroz crudo', '1/4 taza'),
      a('Huevo', '1'),
      v('Jitomate', '6'),
      v('Cebolla', '1'),
      v('Ajo', '2 dientes'),
      v('Zanahoria', '2'),
      v('Calabaza', '2'),
      v('Hierbabuena', 'unas hojas'),
      a('Caldo de pollo en polvo', '1 cucharada'),
    ],
    pasos: [
      'Mezcla la carne con el arroz crudo, el huevo, sal, pimienta y la hierbabuena picada. Haz bolitas del tamaño de una nuez grande.',
      'Licua los jitomates con medio ajo y un pedazo de cebolla. Cuélalo si quieres el caldillo más ligero.',
      'En una olla con un poco de aceite, echa la salsa y deja que hierva 5 minutos.',
      'Agrega 4 tazas de agua con el caldo en polvo y espera a que suelte el hervor.',
      'Mete las albóndigas una por una sin moverlas. Tapa y déjalo 25 minutos a fuego bajo.',
      'A los 15 minutos échale la zanahoria y la calabaza en cubos.',
    ],
  },
  {
    id: 'r-sopa-fideo',
    titulo: 'Sopa de fideo con pollo a la plancha',
    tiempos: ['comida'],
    minutos: 30,
    porciones: 4,
    ingredientes: [
      a('Fideo', '2 paquetes'),
      v('Jitomate', '3'),
      v('Cebolla', '1/4'),
      v('Ajo', '1 diente'),
      c('Pechuga de pollo', '600 g'),
      a('Caldo de pollo en polvo', '1 cucharada'),
      a('Aceite', '2 cucharadas'),
      v('Aguacate', '1'),
    ],
    pasos: [
      'Licua los jitomates con la cebolla y el ajo.',
      'En una olla con aceite, dora el fideo moviéndolo seguido hasta que agarre color dorado. Aguas: se quema rápido.',
      'Échale la salsa licuada —cuidado que salpica— y déjala 3 minutos.',
      'Agrega 4 tazas de agua con el caldo en polvo, tapa y déjalo 10 minutos.',
      'Mientras, salpimenta las pechugas y ponlas en el sartén caliente con poquito aceite, 6 minutos por lado.',
      'Sirve la sopa y el pollo rebanado aparte, con aguacate.',
    ],
  },
  {
    id: 'r-picadillo',
    titulo: 'Picadillo con papa y zanahoria',
    tiempos: ['comida'],
    minutos: 35,
    porciones: 4,
    ingredientes: [
      c('Carne molida de res', '600 g'),
      v('Papa', '3'),
      v('Zanahoria', '2'),
      v('Chícharos', '1 taza'),
      v('Jitomate', '4'),
      v('Cebolla', '1/2'),
      v('Ajo', '2 dientes'),
      a('Arroz', '1 taza'),
      a('Aceite', '2 cucharadas'),
    ],
    pasos: [
      'Pica la papa y la zanahoria en cuadritos chicos, para que se cuezan parejo.',
      'En una olla con aceite, dora la carne molida deshaciéndola con la cuchara, 8 minutos.',
      'Licua los jitomates con la cebolla y el ajo y échaselo a la carne.',
      'Agrega la papa, la zanahoria y los chícharos, media taza de agua y sal. Tapa 20 minutos, moviendo de vez en cuando.',
      'Acompáñalo con arroz blanco o tortillas.',
    ],
    nota: 'Con lo que sobre se rellenan chiles o se hacen empanadas.',
  },
  {
    id: 'r-bistec-encebollado',
    titulo: 'Bistec encebollado',
    tiempos: ['comida'],
    minutos: 25,
    porciones: 4,
    ingredientes: [
      c('Bistec de res', '700 g'),
      v('Cebolla', '2'),
      v('Limón', '2'),
      a('Salsa de soya', '2 cucharadas'),
      a('Aceite', '2 cucharadas'),
      a('Frijoles de la olla', '2 tazas'),
      a('Tortillas', '1 paquete'),
    ],
    pasos: [
      'Rebana la cebolla en tiras no muy delgadas.',
      'Sazona los bisteces con sal, pimienta, el jugo de un limón y la soya. Déjalos 10 minutos.',
      'Calienta bien el sartén con el aceite y pon los bisteces sin encimarlos. 2 minutos por lado, no más, o se ponen duros.',
      'Sácalos y en ese mismo sartén echa la cebolla hasta que se ponga transparente y dulce, 5 minutos.',
      'Regresa la carne, revuelve un minuto y sirve con frijoles y tortillas.',
    ],
  },
  {
    id: 'r-enchiladas',
    titulo: 'Enchiladas verdes',
    tiempos: ['comida', 'cena'],
    minutos: 40,
    porciones: 4,
    ingredientes: [
      a('Tortillas de maíz', '16'),
      c('Pechuga de pollo', '500 g'),
      v('Tomate verde', '12'),
      v('Chile serrano', '2'),
      v('Cebolla', '1'),
      v('Cilantro', 'un manojo'),
      l('Crema', '1 bote'),
      l('Queso fresco', '250 g'),
      a('Aceite', '3 cucharadas'),
    ],
    pasos: [
      'Cuece la pechuga en agua con sal, cebolla y ajo, 25 minutos. Deshébrala.',
      'Hierve los tomates con los chiles 10 minutos y licúalos con cilantro, un pedazo de cebolla y sal.',
      'Calienta la salsa en una olla 5 minutos.',
      'Pasa cada tortilla por aceite caliente unos segundos, nomás para que se ablande, y luego por la salsa.',
      'Rellénalas de pollo, enróllalas y acomódalas en el plato.',
      'Báñalas con más salsa, crema, queso y cebolla en rueditas.',
    ],
  },
  {
    id: 'r-pescado-empapelado',
    titulo: 'Pescado empapelado',
    tiempos: ['comida'],
    minutos: 35,
    porciones: 4,
    ingredientes: [
      c('Filete de pescado', '4'),
      v('Jitomate', '2'),
      v('Cebolla', '1'),
      v('Pimiento', '1'),
      v('Limón', '2'),
      v('Calabaza', '2'),
      a('Aceite de oliva', '2 cucharadas'),
      a('Papel aluminio', '1 rollo'),
    ],
    pasos: [
      'Prende el horno en 200 grados.',
      'Corta un cuadro de aluminio por cada filete. Ponle un chorrito de aceite.',
      'Acomoda el filete, sal, pimienta y limón. Encima jitomate, cebolla, pimiento y calabaza en rebanadas delgadas.',
      'Cierra el aluminio como un paquetito, bien sellado, y mételo al horno 20 minutos.',
      'Se abre en la mesa: sale con su propio jugo.',
    ],
    nota: 'Es de las más sanas y casi no ensucia trastes.',
  },
  {
    id: 'r-fajitas',
    titulo: 'Fajitas de pollo',
    tiempos: ['comida', 'cena'],
    minutos: 30,
    porciones: 4,
    ingredientes: [
      c('Pechuga de pollo', '700 g'),
      v('Pimiento', '2'),
      v('Cebolla', '1'),
      a('Tortillas de harina', '12'),
      l('Queso manchego rallado', '200 g'),
      a('Salsa de soya', '2 cucharadas'),
      v('Limón', '2'),
      a('Aceite', '2 cucharadas'),
    ],
    pasos: [
      'Corta el pollo en tiras y sazónalo con sal, pimienta, soya y limón. Déjalo 10 minutos.',
      'Corta los pimientos y la cebolla en tiras.',
      'Calienta bien el sartén, echa el pollo y déjalo sin mover 3 minutos para que dore. Luego revuelve otros 5.',
      'Sácalo y en el mismo sartén cocina las verduras 5 minutos: deben quedar con algo de crujido.',
      'Junta todo, calienta las tortillas y arma en la mesa con queso.',
    ],
  },
  {
    id: 'r-chuletas',
    titulo: 'Chuletas de puerco con ensalada',
    tiempos: ['comida'],
    minutos: 25,
    porciones: 4,
    ingredientes: [
      c('Chuletas de puerco', '4'),
      v('Lechuga', '1'),
      v('Jitomate', '2'),
      v('Pepino', '1'),
      v('Limón', '2'),
      a('Aceite de oliva', '2 cucharadas'),
      a('Arroz', '1 taza'),
    ],
    pasos: [
      'Sazona las chuletas con sal, pimienta y limón.',
      'Calienta el sartén bien caliente con poquito aceite y ponlas 4 minutos por lado. No las muevas mientras doran.',
      'Déjalas reposar 5 minutos antes de servir: así quedan jugosas.',
      'Para la ensalada: lechuga, jitomate y pepino picados, con aceite, limón y sal.',
    ],
  },
  {
    id: 'r-caldo-pollo',
    titulo: 'Caldo de pollo con verduras',
    tiempos: ['comida', 'cena'],
    minutos: 50,
    porciones: 4,
    ingredientes: [
      c('Piezas de pollo', '4'),
      v('Zanahoria', '3'),
      v('Calabaza', '3'),
      v('Papa', '2'),
      v('Chayote', '1'),
      v('Cebolla', '1/2'),
      v('Ajo', '2 dientes'),
      v('Cilantro', 'un manojito'),
      v('Limón', '3'),
      a('Arroz', '1/2 taza'),
    ],
    pasos: [
      'Pon el pollo en una olla grande con agua que lo cubra, la cebolla, el ajo y sal. Deja que hierva y quítale la espuma de arriba con una cuchara.',
      'Baja el fuego y déjalo 25 minutos.',
      'Echa las verduras partidas en trozos grandes y el arroz. 20 minutos más.',
      'Sirve con cilantro picado, limón y tortillas.',
    ],
    nota: 'El de siempre cuando alguien anda malito.',
  },
  {
    id: 'r-pasta-crema',
    titulo: 'Pasta con crema y jamón',
    tiempos: ['comida', 'cena'],
    minutos: 25,
    porciones: 4,
    ingredientes: [
      a('Pasta (espagueti o coditos)', '500 g'),
      l('Crema', '1 bote'),
      l('Queso manchego rallado', '200 g'),
      c('Jamón', '250 g'),
      v('Champiñones', '200 g'),
      v('Ajo', '2 dientes'),
      l('Mantequilla', 'un trozo'),
    ],
    pasos: [
      'Pon a hervir agua con sal. Cuando burbujee fuerte, echa la pasta y cuécela los minutos que diga la bolsa.',
      'Mientras, derrite la mantequilla en un sartén con el ajo picado.',
      'Echa el jamón en cuadritos y los champiñones rebanados. 5 minutos.',
      'Baja el fuego, agrega la crema y el queso y mueve hasta que se haga una salsa. No la dejes hervir fuerte.',
      'Escurre la pasta y revuélvela con la salsa.',
    ],
    nota: 'La favorita de las niñas y es de las más fáciles.',
  },

  // ------------------------------------------------------------------ cena
  {
    id: 'r-tostadas-frijol',
    titulo: 'Tostadas de frijol con queso',
    tiempos: ['cena'],
    minutos: 10,
    porciones: 4,
    ingredientes: [
      a('Tostadas', '1 paquete'),
      a('Frijoles refritos', '2 tazas'),
      l('Queso fresco', '200 g'),
      l('Crema', '1 bote chico'),
      v('Lechuga', '1/2'),
      v('Aguacate', '1'),
      v('Jitomate', '1'),
    ],
    pasos: [
      'Calienta los frijoles.',
      'Unta cada tostada y ponle lechuga picada, jitomate, crema, queso y aguacate.',
    ],
  },
  {
    id: 'r-tortas',
    titulo: 'Tortas de jamón y queso',
    tiempos: ['cena'],
    minutos: 15,
    porciones: 4,
    ingredientes: [
      a('Bolillos', '4'),
      c('Jamón', '300 g'),
      l('Queso manchego', '200 g'),
      v('Aguacate', '2'),
      v('Jitomate', '2'),
      v('Lechuga', '1/2'),
      a('Chiles en vinagre', '1 lata chica'),
      l('Mayonesa', 'al gusto'),
    ],
    pasos: [
      'Parte los bolillos y úntalos de mayonesa.',
      'Pon jamón, queso, aguacate, jitomate y lechuga.',
      'Si los quieres calientes, ponlos un momento en el comal aplastados con algo pesado.',
    ],
  },
  {
    id: 'r-sopa-verduras',
    titulo: 'Sopa de verduras',
    tiempos: ['cena'],
    minutos: 30,
    porciones: 4,
    ingredientes: [
      v('Zanahoria', '2'),
      v('Calabaza', '3'),
      v('Papa', '2'),
      v('Ejotes', '200 g'),
      v('Elote', '1'),
      v('Jitomate', '3'),
      v('Cebolla', '1/4'),
      v('Ajo', '1 diente'),
      a('Caldo de pollo en polvo', '1 cucharada'),
    ],
    pasos: [
      'Pica todas las verduras en cuadritos parejos.',
      'Licua el jitomate con la cebolla y el ajo y ponlo a hervir 5 minutos en la olla con un poco de aceite.',
      'Agrega 6 tazas de agua con el caldo en polvo.',
      'Echa las verduras y déjalas 20 minutos, hasta que la zanahoria se sienta suave.',
    ],
  },
  {
    id: 'r-fruta-yogur',
    titulo: 'Fruta con yogur y granola',
    tiempos: ['cena', 'almuerzo'],
    minutos: 10,
    porciones: 4,
    ingredientes: [
      l('Yogur natural', '1 litro'),
      a('Granola', '2 tazas'),
      v('Fresas', '250 g'),
      v('Plátano', '2'),
      v('Manzana', '2'),
      a('Miel', 'al gusto'),
    ],
    pasos: [
      'Pica la fruta.',
      'Sirve el yogur en vasos, encima la fruta, luego granola y un hilito de miel.',
    ],
    nota: 'Para las noches en que ya nadie tiene hambre de verdad.',
  },
]

export const TIEMPOS: { id: Tiempo; nombre: string }[] = [
  { id: 'almuerzo', nombre: 'Almuerzo' },
  { id: 'comida', nombre: 'Comida' },
  { id: 'cena', nombre: 'Cena' },
]

export const PASILLOS: { id: Pasillo; nombre: string }[] = [
  { id: 'verdura', nombre: 'Frutas y verduras' },
  { id: 'carne', nombre: 'Carnes y pollo' },
  { id: 'lacteos', nombre: 'Lácteos y huevo' },
  { id: 'abarrotes', nombre: 'Abarrotes' },
  { id: 'otros', nombre: 'Otros' },
]

export const nombreTiempo = (t: Tiempo) => TIEMPOS.find(x => x.id === t)?.nombre ?? t
export const nombrePasillo = (p: Pasillo) => PASILLOS.find(x => x.id === p)?.nombre ?? 'Otros'
